######################################################################
# Automatically generated by qmake (3.0) Sun Apr 15 14:04:12 2018
######################################################################

TEMPLATE = app
TARGET = takbeer
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
